moving to openapi-dependencies
defenseunicorns/gojsonschema pull request #1
Opened 2023-11-15 15:15 UTC by AustinAbro321

2023-11-15 15:59 UTC, bdw617 requested changes

2023-11-15 15:59 UTC, bdw617 commented on schemaLoader.go
> +	emptyRef, _ := jsonreference.New("")
```suggestion
	emptyRef, err := jsonreference.New("")
	if err != nil {
	        return err
	}
```

2023-11-15 16:32 UTC, lucasrod16 requested changes
We should update all references to `xeipuuv` in README.md.

Examples:
 - `go get github.com/xeipuuv/gojsonschema` -> `go get github.com/defenseunicorns/gojsonschema`
 
 - `github.com/xeipuuv/gojsonreference` -> `github.com/go-openapi/gojsonreference`
 
 There are many other references to `xeipuuv` throughout the repository. `glide.yaml`, `LICENSE.APACHE-2.0.txt`, and all of the copyright statements in `*.go` files. I'm not sure whether we want to or should update them or not. @Racer159 thoughts?

2023-11-15 17:43 UTC, AustinAbro321 commented
Ah good point @lucasrod16. Yeah those should be updated. I'm also not sure about the copyright statements. 

I believe I should make the change from `go get github.com/xeipuuv/gojsonschema` to `go get github.com/gojsonschema/gojsonschema` since we plan on contributing back to https://github.com/gojsonschema/gojsonschema

In that case in our code I think we should use the go mod replace functionality to point it back to our defense unicorns fork?

2023-11-15 19:29 UTC, Racer159 commented
The README should be updated for sure - the copyrights will need to have xeipuuv attribution in them still, but could have `, and the gojsonschema authors` added - https://www.apache.org/licenses/LICENSE-2.0.html#redistribution

2023-11-15 19:29 UTC, Racer159 commented
And yes it would be to https://github.com/gojsonschema/gojsonschema so we can PR back to that repo

2023-11-15 23:54 UTC, lucasrod16 approved these changes
lgtm

2023-11-16 00:18 UTC, bdw617 requested changes

2023-11-16 00:18 UTC, bdw617 commented on schemaPool.go
> +	refToURL, _ := jsonreference.New(reference.String())
please check the error here and it looks perfect.

2023-11-16 00:22 UTC, bdw617 commented on schemaPool.go
> +	refToURL, _ := jsonreference.New(reference.String())
I'll let this go, gosec didn't complain

2023-11-16 00:22 UTC, bdw617 approved these changes

2023-11-16 00:34 UTC, merged